spring:
  application:
    name: dubbo-provider
dubbo:
  application:
    id: dubbo-provider
    name: dubbo-provider
  registry:
    # 连接多个或一个地址都可以。因为使用的是集群
#    address: zookeeper://www.youngeryang.top:2181;zookeeper://www.youngeryang.top:2182;zookeeper://www.youngeryang.top:2183
    address: zookeeper://www.youngeryang.top:2183
    timeout: 12000
  protocol:
    name: dubbo
    port: 20880
